## MATHEMATICAL COMPUTING GROUP WORK ASSIGNMENT
### GROUP MEMBERS REG NUMBERS:
1. 2024/DSC/0038/SS
2. 2024/DSC/0071/SS
3. 2024/DSC/0055/SS
4. 2024/DSC/0034/SS
5. 2024/DSC/0051/SS
6. 2023/DCSE/0070/SS
7. 2024/DSC/0054/SS
8. 2024/DSC/00102/SS
9. 2024/DSC/0096/SS
10. 2023/DCSE/0026/SS
11. 2024/DSC/0036/SS
12. 2024/DSC/0022/SS
13. 2024/DSC/0013/SS
14. 2024/DSC/0026/SS


# number_one

In [1]:
import numpy as np

In [2]:
matrix_A = np.array([[2,2,3],[-2,7,4],[-3,-3,-4],[-8,2,3]])
print(matrix_A)

[[ 2  2  3]
 [-2  7  4]
 [-3 -3 -4]
 [-8  2  3]]


## (I)

In [3]:
new_column = np.array([[1],[0],[1],[1]]) # adding a new column
new_matrix = np.hstack((matrix_A,new_column)) #hstack adds a column in a matrix
print(new_matrix)

[[ 2  2  3  1]
 [-2  7  4  0]
 [-3 -3 -4  1]
 [-8  2  3  1]]


In [4]:
determinant = np.linalg.det(new_matrix) # proving the invertable conditions
print(determinant)

-289.99999999999994


## (II)

In [5]:
matrix_A = np.array([[2,2,3],[-2,7,4],[-3,-3,-4],[-8,2,3]])
reduced_matrix = np.delete(matrix_A,3,axis=0) #removing a row in the 4th position
print(reduced_matrix)

[[ 2  2  3]
 [-2  7  4]
 [-3 -3 -4]]


In [6]:
determinant = np.linalg.det(reduced_matrix) # proving the invertable conditions
print(determinant)

9.000000000000005


## (III)

In [7]:
A = np.array([[2,2,3],[-2,7,4],[-3,-3,-4],[-8,2,3]])
AT = np.transpose(A) # Find the transpose of A
print(AT)

[[ 2 -2 -3 -8]
 [ 2  7 -3  2]
 [ 3  4 -4  3]]


In [8]:
AAT = np.dot(A,AT) # Find the product of AAT
print(AAT)

[[ 17  22 -24  -3]
 [ 22  69 -31  42]
 [-24 -31  34   6]
 [ -3  42   6  77]]


In [98]:
determinant = np.linalg.det(product_matrix)
determinant

np.float64(3.3772984409097314e-12)

Yes, AAT is invertable because their product is a square matrix and their determinant is not equal to zero

## or

In [9]:
determinant = np.linalg.det(AAT)
if determinant != 0 :
    print("Product Matrix is invertible.")
else:
    print("Product Matrix is not invertible.")

Product Matrix is invertible.


## (IV)

In [12]:
A = np.array([[2,2,3],[-2,7,4],[-3,-3,-4],[-8,2,3]])
A_T = np.transpose(A) # Find the transpose of A
print(A)

[[ 2  2  3]
 [-2  7  4]
 [-3 -3 -4]
 [-8  2  3]]


In [13]:
print(A_T)

[[ 2 -2 -3 -8]
 [ 2  7 -3  2]
 [ 3  4 -4  3]]


In [14]:
ATA = np.dot(A_T,A) # Find the product of AAT
print(ATA)

[[ 81 -17 -14]
 [-17  66  52]
 [-14  52  50]]


In [16]:
determinant = np.linalg.det(ATA)
print(determinant)

45642.00000000001


Yes, ATA is invertable because the determinant of A and A_T is not equal to zero.

# NUMBER TWO

In [17]:
import numpy as np
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

## the shape of X

In [104]:
shape_x = X.shape
print(shape_x)

(3, 2)


## transpose of x

In [19]:
transpose = np.transpose(X) # find the transpose of x
print(transpose)

[[25  5  3]
 [ 2 26  7]]


#### or

In [106]:
transpose2 = X.T
print(transpose2)

[[25  5  3]
 [ 2 26  7]]


## generating a new n-d array

In [107]:
X = np.array([[25, 2], [5, 26], [3, 7]])
X_scalar = np.dot(3,X)
print(X)


[[25  2]
 [ 5 26]
 [ 3  7]]


In [108]:
print(X_scalar)

[[75  6]
 [15 78]
 [ 9 21]]


## generate new matrix A and computing the matrix multiplication of X and A

In [21]:
A = np.array([[3,4], [5,6], [7,8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

Multiplying the transpose of x with matrix A so as to obey the laws of multiplication of matrices.

In [22]:
product_matrix = np.dot(transpose,A)
print(product_matrix)

[[121 154]
 [185 220]]


## inverse of a matrix

In [115]:
inverse_matrix = np.linalg.inv(product_matrix) # inverse of XA
print(inverse_matrix)

[[-0.11764706  0.09893048]
 [ 0.08235294 -0.06470588]]


In [116]:
inverse_matrix = np.linalg.inv(matrix_product) # inverse of XA
print(inverse_matrix)

[[-0.11764706  0.08235294]
 [ 0.09893048 -0.06470588]]


# NUMBER THREE

## (i)

In [12]:
x = np.array([25, 2, 5])
print(x)

[25  2  5]


## (ii)

## shape of array x

In [8]:
print(x.shape)   

(3,)


## (iii)

## transpose

In [10]:
x_transpose = np.transpose(x) # find the transpose of x
print(x_transpose)

[25  2  5]


## (iv) L^2 norm

In [13]:
norm_x = np.linalg.norm(x)
print(norm_x)

25.573423705088842
